### ISSUE TITLE
ödənişli support

### ISSUE THREAD

**Issue by onlineoyren** [hmammadov/woocommerce-millikart-payment#3]
Salam,
Siz, ödənişli support eliyirsiz?

**Comment by hmammadov** [comment]
Здравствуйте!

На данный момент занят другими проектами. Поэтому не знаю, когда смогу заняться этим плагином. Возможно проблемы возникают из-за несовместимости с новой версией Woocommerce или даже новой версии WordPress.

Ориентировочно этим плагином займусь не ранее февраля.

Если Вам нужно срочно, можете написать мне в скайп - esttable

Даже если не лично, то посоветую ребят, которые установят и настроят MilliKart на Ваш сайт (конечно не бесплатно).
